server:
  servlet:
    context-path: /sell
  port: 8090
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://192.168.0.51:3306/sellorder?characterEncoding=utf-8
    username: root
    password: 123456
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: NON_NULL
  redis:
    host: 192.168.0.51
    port: 6379
    
mybatis:
  mapper-locations: classpath:/mapper/*.xml
    
wechat:
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 47ccc303338cee6e62894fxxxxxxxxxxx
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://localhost:8080/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

project-url:
  wechatMpAuthorize: http://localhost:8090
  wechatOpenAuthorize: http://localhost:8090
  sell: http://localhost:8090
